name: ci

# when to run the ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      # clone repo in runner
      - uses: actions/checkout@v5

      # efficient nix installer & caching
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      # check that nix files are formatted
      - name: check nix formatting
        run: nix run nixpkgs#alejandra -- --check .

      # ensure all inputs/outputs are right
      - name: check flake
        run: nix flake check

  build:
    name: build
    runs-on: ubuntu-latest
    # wait for lint job to pass
    needs: lint
    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: compile typst pdf
        run: nix develop --command typst compile main.typ

      - name: create index.html
        run: |
          echo '<!DOCTYPE html><html><body style="margin:0"><embed src="main.pdf" type="application/pdf" width="100%" height="100vh" style="height:100vh;"></body></html>' > index.html

      - name: Upload for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          # upload main.pdf & index.html
          path: .

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4
